/*
  # Create call_logs table

  1. New Tables
    - `call_logs`
      - `id` (bigint, primary key, auto-generated)
      - `created_at` (timestamptz, default now)
      - `phone_number` (text) - caller's phone number
      - `duration_seconds` (integer) - call duration
      - `transcript` (text) - full call transcript
      - `summary` (text) - call outcome summary
      - `recording_url` (text) - URL to call recording
      - `caller_name` (text) - caller's name from SIP/CID
      - `sentiment` (text) - AI-detected sentiment
      - `estimated_cost_usd` (numeric) - estimated call cost
      - `call_date` (date) - date of call in IST
      - `call_hour` (integer) - hour of call in IST
      - `call_day_of_week` (text) - day name
      - `was_booked` (boolean) - whether booking was made
      - `interrupt_count` (integer) - times caller interrupted agent
      - `audio_codec` (text) - audio codec used
      - `call_direction` (text) - inbound or outbound
      - `campaign_id` (text) - outbound campaign identifier
  2. Security
    - Enable RLS on `call_logs` table
    - Add policy for authenticated users to read their own data
    - Add policy for service role operations via anon key
*/

CREATE TABLE IF NOT EXISTS call_logs (
    id bigint generated by default as identity primary key,
    created_at timestamptz DEFAULT now() NOT NULL,
    phone_number text,
    duration_seconds integer DEFAULT 0,
    transcript text DEFAULT '',
    summary text DEFAULT '',
    recording_url text DEFAULT '',
    caller_name text DEFAULT '',
    sentiment text DEFAULT 'unknown',
    estimated_cost_usd numeric(10,5) DEFAULT 0,
    call_date date,
    call_hour integer,
    call_day_of_week text DEFAULT '',
    was_booked boolean DEFAULT false,
    interrupt_count integer DEFAULT 0,
    audio_codec text DEFAULT '',
    call_direction text DEFAULT 'inbound',
    campaign_id text DEFAULT ''
);

ALTER TABLE call_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read call_logs"
  ON call_logs FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Anon can insert call_logs"
  ON call_logs FOR INSERT
  TO anon
  WITH CHECK (true);

CREATE POLICY "Anon can read call_logs"
  ON call_logs FOR SELECT
  TO anon
  USING (true);

CREATE INDEX IF NOT EXISTS idx_call_logs_phone ON call_logs (phone_number);
CREATE INDEX IF NOT EXISTS idx_call_logs_date ON call_logs (call_date);
CREATE INDEX IF NOT EXISTS idx_call_logs_direction ON call_logs (call_direction);
CREATE INDEX IF NOT EXISTS idx_call_logs_campaign ON call_logs (campaign_id);
